<form id="frmRegister" action="<?php echo $this->element->getAction();?>" method="<?php echo $this->element->getMethod();?>">
    <label>E-mail</label>
    <?php echo $this->element->email?>

    <label>Username</label>
    <?php echo $this->element->username?>
    
    <label>Zip</label>
    <?php echo $this->element->zip?>

    <label>Password</label>
    <?php echo $this->element->pswd ?>
    
    <br />
    <?php echo $this->element->submit ?>
</form>


