<form id="frmLogin" action="<?php echo $this->element->getAction();?>" method="<?php echo $this->element->getMethod();?>">
    <label>E-mail</label>
    <?php echo $this->element->email?>

    <label>Password</label>
    <?php echo $this->element->pswd ?>

    <label>Public</label>
    <?php echo $this->element->public ?>
    
    <br />
    <?php echo $this->element->submit ?>
</form>


