<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<style type="text/css" > 
#map 
{
    border: 1px solid black;
    width: 400px;
    height: 300px
}
</style>

<script type="text/javascript">
    function initialize()
    {
        var latlng = new google.maps.LatLng(39.984577, -83.018692);
        var options = {
            zoom: 12,
            center: latlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map"), options);
    }
</script>
<br /><br />
<div id="view-content">
    <p>View script for controller <b>Account</b> and script/action name <b>map</b></p>
    <div id="map"></div>
    <script>initialize()</script>
</div>