<br /><br />
<div id="view-content">
	<p>View script for controller <b>Account</b> and script/action name <b>show</b></p>
       
        <h1><?php echo $this->item->Title;?></h1>
        <img src="<?php echo $this->item->MediumImage->Url;?>" />
        <p><strong>Publisher</strong>: <?php echo $this->item->Author;?></p>
        <p><strong>Release Date</strong>: <?php echo $this->item->ReleaseDate;?></p>
        <p><strong>Latest Rank</strong>: <?php echo $this->item->SalesRank;?></p>
</div>